apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app: {{ .Values.name }}
    app-group: submit-app
data:
  crontab: |
    {{ .Values.cronTab }}
  WEB_URL: {{ .Values.web.url }}
